name: E2E-Test
on: [workflow_call, workflow_dispatch]
jobs:
  E2E-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}
      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install
      - name: Running E2E Test
        run: yarn test:e2e --URL=${{ github.ref== 'refs/heads/main'&&'http://cicd.github.migaox.com/'|| 'http://cicd.staging.github.migaox.com/'}}
